### ISSUE TITLE
Copying TX hash

### ISSUE THREAD

**Issue by Nathanwoodburn** [pinheadmz/palmreader#5]
The tx hash for a multisig is generated and shown like so
![image](https://user-images.githubusercontent.com/62039630/173232036-64759fde-2a35-4a27-a0ef-a06a595879a6.png)

Clicking Copy doesn't work on Windows and copying the hash from the screen gives

 `00000000017d23113c2cb72ebc0dba1436dc9329beff9bbb6072e8eb8ce05c8b5e9e4f1c7f00000000ffffffff0240420f000000000000149e989543                   │                                                                           │ │ 7d23113c    6/12/2022, 21:47:52     1            10.000000                 │                   2ab44d4adc95717ff8966dc3031a15e90000c8d18800000000000020854ea05d0c72e82f404f92ca0648650fc4955d14ee3d46748def719d9600a954                   │                                                                           │ │                                                                            │                   00000000000004000041394965b82247e41d742713ebe36363789b1ea8e17d0b4dbd020b1b8b76384a6c25fd7069c245a268e1eac542c48c8c2372c3                   │                                                                           │ │                                                                            │                   a7766ea81f93fc0f22f97d76226f0147522102decdb1acc25120b26a610a88c5a01aa183bae1770fc6614cb6bee4c7bf85cc952103d27471684dde07                   │                                                                           │ │                                                                            │                   2b139419e90de9e7b7c07dd61486e47538eadb8f0a6baa483352ae`
 
This is because it copies text from the rest of the screen.

Possible fix ideas
1. Add button to show screen with only that text in 1 line with ENTER or ESC returning to normal
2. Save to file
3. Add copying to windows (Probs quite a pain)

**Comment by pinheadmz** [comment]
Copying requires xclip or pbcopy installed on the system. I'm going to add a "export as file" feature soon.

**Comment by pinheadmz** [comment]
fixed in 4ddca25 and e607b85
