### ISSUE TITLE
Copy and Paste over SSH

### ISSUE THREAD

**Issue by magicstone1412** [pinheadmz/palmreader#9]
**There are no issues here. Just share some experiences when using Palm Reader.**

I like Palm Reader because it's lightweight, and can be installed on a headless machine. It has all the features (including a multisig wallet)  I need at this moment. Hopefully, it will be further developed in the future.

I use MS Windows, Orange Pi Board (arm64), and Nano Ledger S.

Copy and Paste over SSH is an essential feature. To use this, the ssh program needs to have the X11 forwarding feature. I used Mobaxterm and installed some packages to be able to copy and paste into Palm Reader.

On Orange PI make sure that `X11Forwarding yes` must specified in `/etc/ssh/sshd_config`.

Install `xsel` package to support copy

```
$ sudo apt install xsel
``` 

X11 on Debian/Ubuntu

```
$ sudo apt install xauth xfonts-base
```

To copy, click on the content you wanna to copy, a message saying that copying to the clipboard is successful.

To paste content from Windows into the Palm Reader, leave the cursor in the SSH window and press `SHIFT + Right Click` to get a paste option.

![2022-10-04 19_04_37-](https://user-images.githubusercontent.com/9553811/193831172-78fd2157-0eb7-46e2-8dba-6797d849ceac.png)

From now on I can use my Pi board as a key of multisign wallet or interact with the Handshake blockchain however I want.

P/S: If you are Vietnamese, visit [my blog](https://skywirex.com) to read more about Handshake. Goodluck all.

Reference:

https://superuser.com/questions/1405848/understanding-x11-forwarding-through-ssh-start-to-finish-steps

**Comment by pinheadmz** [comment]
Thanks for trying palm reader and especially over SSH, that's a cool use case. Would you be willing to add these notes about copy/paste to the README of the repo? Open a pull request and we can discuss

**Comment by magicstone1412** [comment]
Thank you. I will do it
